"""Language-specific tree-sitter query configurations."""

# Maps language name to tree-sitter grammar name used by tree-sitter-language-pack
GRAMMAR_NAMES = {
    "python": "python",
    "javascript": "javascript",
    "typescript": "typescript",
    "java": "java",
    "go": "go",
    "rust": "rust",
    "c": "c",
    "cpp": "cpp",
    "ruby": "ruby",
    "php": "php",
}

# Node type mappings per language — what tree-sitter node types correspond to classes, functions, etc.
LANGUAGE_CONFIGS = {
    "python": {
        "class_types": ["class_definition"],
        "function_types": ["function_definition"],
        "import_types": ["import_statement", "import_from_statement"],
        "variable_types": ["assignment", "augmented_assignment"],
        "call_types": ["call"],
        "name_field": "name",
        "body_field": "body",
        "params_field": "parameters",
        "superclass_field": "superclasses",
    },
    "javascript": {
        "class_types": ["class_declaration", "class"],
        "function_types": ["function_declaration", "method_definition", "arrow_function", "function"],
        "import_types": ["import_statement"],
        "variable_types": ["variable_declaration", "lexical_declaration"],
        "call_types": ["call_expression"],
        "name_field": "name",
        "body_field": "body",
        "params_field": "parameters",
        "superclass_field": "heritage",
    },
    "typescript": {
        "class_types": ["class_declaration", "class", "abstract_class_declaration"],
        "function_types": ["function_declaration", "method_definition", "arrow_function", "function"],
        "import_types": ["import_statement"],
        "variable_types": ["variable_declaration", "lexical_declaration"],
        "call_types": ["call_expression"],
        "name_field": "name",
        "body_field": "body",
        "params_field": "parameters",
        "superclass_field": "heritage",
    },
    "java": {
        "class_types": ["class_declaration", "interface_declaration", "enum_declaration"],
        "function_types": ["method_declaration", "constructor_declaration"],
        "import_types": ["import_declaration"],
        "variable_types": ["field_declaration"],
        "call_types": ["method_invocation"],
        "name_field": "name",
        "body_field": "body",
        "params_field": "parameters",
        "superclass_field": "superclass",
    },
    "go": {
        "class_types": ["type_declaration"],
        "function_types": ["function_declaration", "method_declaration"],
        "import_types": ["import_declaration"],
        "variable_types": ["var_declaration", "const_declaration", "short_var_declaration"],
        "call_types": ["call_expression"],
        "name_field": "name",
        "body_field": "body",
        "params_field": "parameters",
        "superclass_field": None,
    },
    "rust": {
        "class_types": ["struct_item", "enum_item", "trait_item", "impl_item"],
        "function_types": ["function_item"],
        "import_types": ["use_declaration"],
        "variable_types": ["let_declaration", "const_item", "static_item"],
        "call_types": ["call_expression"],
        "name_field": "name",
        "body_field": "body",
        "params_field": "parameters",
        "superclass_field": None,
    },
    "c": {
        "class_types": ["struct_specifier", "enum_specifier", "union_specifier"],
        "function_types": ["function_definition"],
        "import_types": ["preproc_include"],
        "variable_types": ["declaration"],
        "call_types": ["call_expression"],
        "name_field": "declarator",
        "body_field": "body",
        "params_field": "parameters",
        "superclass_field": None,
    },
    "cpp": {
        "class_types": ["class_specifier", "struct_specifier", "enum_specifier"],
        "function_types": ["function_definition"],
        "import_types": ["preproc_include"],
        "variable_types": ["declaration"],
        "call_types": ["call_expression"],
        "name_field": "declarator",
        "body_field": "body",
        "params_field": "parameters",
        "superclass_field": "base_class_clause",
    },
    "ruby": {
        "class_types": ["class", "module"],
        "function_types": ["method", "singleton_method"],
        "import_types": ["call"],  # require/require_relative
        "variable_types": ["assignment"],
        "call_types": ["call", "method_call"],
        "name_field": "name",
        "body_field": "body",
        "params_field": "parameters",
        "superclass_field": "superclass",
    },
    "php": {
        "class_types": ["class_declaration", "interface_declaration", "trait_declaration"],
        "function_types": ["function_definition", "method_declaration"],
        "import_types": ["namespace_use_declaration"],
        "variable_types": ["property_declaration"],
        "call_types": ["function_call_expression", "member_call_expression"],
        "name_field": "name",
        "body_field": "body",
        "params_field": "parameters",
        "superclass_field": "base_clause",
    },
}
